uri:
  kakao:
    auth: https://kauth.kakao.com
    api: https://kapi.kakao.com

logging:
  level:
    org.springframework:
      web.client: debug
      security: debug

jwt:
  secret: <my-secret>

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: <kakao_developers-요약정보-REST_API_키>
            client-name: Kakao
            client-secret: <kakao_developers-카카오로그인-보안-Client_Secret-코드>
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/api/auth/{action}/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
              - birthday
        provider:
          kakao:
           authorization-uri: ${uri.kakao.auth}/oauth/authorize
           token-uri: ${uri.kakao.auth}/oauth/token
           user-info-uri: ${uri.kakao.api}/v2/user/me
           user-info-authentication-method: GET
           user-name-attribute: id
